### ISSUE TITLE
SassDoc

### ISSUE THREAD

**Issue by lockz** [20Tauri/DoxyDoxygen#37]
Default value not working. Only mixins are parsed, functions ignored. Sublime text 3 (3083) DoxyDoxygen 0.32.2.

**Comment by 20Tauri** [comment]
Thank for reporting
Default value will be improved in 0.33.2 (just released)
Sass and SassDoc support have also been improved.

Functions are parsed on my side (see example belove).
Do you use "Syntax highlight for Sass" plugin as recommended ?

``` scss
/**
 * { function_description }
 *
 * @param      {<type>}  $color               - { description }
 * @param      {<type>}  $state  [<default>]  - { description }
 *
 * @return     {<type>}
 */
@function color-modify($color, $state: 'hover') {
    @if $state == "hover" {
        $color: tint($color, 20%);
    } @elseif $state == "active" {
        $color: shade($color, 20%);
    } @elseif $state == "disabled" {
        $color: tint(desaturate($color, 70%), 20%);
    }

    @return $color;
}
```
